### ISSUE TITLE
LaTeX compile error: file not found

### ISSUE THREAD

**Issue by mjavadhpour** [ineshbose/simple-icons-latex#10]
Hi guys, I just start using this package and thank you for your works.

I have compile error and this is the compiler log:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex 2022.7.25)  2 AUG 2022 14:44

Package: simpleicons 2022/07/29 7.5.0 Simple Icons 7.5.0 Logos


! LaTeX Error: File `simpleiconsglyphs-pdftex.tex' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: tex)
```

**Comment by ineshbose** [comment]
Hi @mjavadhpour! Thank you for opening an issue on this repository and sharing your error. May I know more about your environment, how the package was installed and a MWE if possible please?

**Comment by mjavadhpour** [comment]
The project that I tried to used this package is public and is dockerized so let me know if it would be helpful to share it with you.

**Comment by ineshbose** [comment]
Thanks for the info! MWE stands for "Minimal Reproducible Example" which could help get the same error as you.
If I'm not wrong, would it be this repo - https://github.com/mjavadhpour/resm?

Please give me a while before I get some time to investigate and get back to you. I'm no LaTeX expert but I'll do my best!

**Comment by mjavadhpour** [comment]
Yes it is. 

Thank you for the description about MWE.

**Comment by ineshbose** [comment]
I've found out that the archive `tlmgr` uses to install the package somehow doesn't include that file.

https://mirror.las.iastate.edu/tex-archive/systems/texlive/tlnet/archive/simpleicons.tar.xz

Please bear with me while I try and resolve this.

**Comment by ineshbose** [comment]
Hi @mjavadhpour,

My sincere apologies for the delay. I had to get in contact with the installers on these mirrors since there was a misunderstanding, about the file to be part of the doc branch and not runtime, that needed to be cleared up.

The file is there on the archive now, and I would like you to ask you to reinstall the package and confirm that it is now working on your end (and close the issue). 🙂

**Comment by mjavadhpour** [comment]
Hi @ineshbose, Thank you for following up the problem, I test it and it works as intended. 👍
