### ISSUE TITLE
Renaming \SI

### ISSUE THREAD

**Issue by pnsaeta** [ineshbose/simple-icons-latex#12]
I love this package, but it collides with the siunitx package, which defines the \SI command. I have hacked my copy, changing the \SI command to \SIc, and making the corresponding updates to simpleiconsglyphs-xeluatex.tex.

**Comment by pnsaeta** [comment]
Would it not be possible to alter your package to avoid this conflict? Please!

**Comment by ineshbose** [comment]
Hi @pnsaeta,

Thanks a lot for opening an issue here and bringing this to my notice. I sincerely apologise for not responding earlier as I was on holiday. I shall surely get into renaming the command to avoid future conflicts and hope to release it by Friday (if Simple Icons also release a new version).
