### ISSUE TITLE
The simpleicons do not work with xelatex on Windows

### ISSUE THREAD

**Issue by hair-splitter** [ineshbose/simple-icons-latex#17]
The xelatex compiler does not find the SimpleIcons.otf file on Windows. The solution is that you should replace the code
`\newfontfamily{\simpleiconsmap}{SimpleIcons}`
with 
`\newfontfamily{\simpleiconsmap}{SimpleIcons.otf}`
 in the simpleicons.sty.

**Comment by ineshbose** [comment]
(Release should happen in the next 24 hours)
