### ISSUE TITLE
Glyphs not in line

### ISSUE THREAD

**Issue by ineshbose** [ineshbose/simple-icons-latex#2]
The character seems to be in the correct position, but the glyphs themselves are appearing below the line.

**Comment by eburghar** [comment]
I confirm the bug. I use this as a temporary fix.
```latex
\newcommand{\simpleIcon}[2][1]{%
  \raisebox{1.2\fontcharht\font`0}{%
    \simpleicon{#2}%
  }%
}
```

**Comment by ineshbose** [comment]
Thank you for confirming the bug and using this package - it means a lot.

I'm still investigating for solutions, but I have kept a note for this approach! 😄

**Comment by eburghar** [comment]
I think this is a bug with the way the font is constructed. The glyphs are set below the baseline.

**Comment by eburghar** [comment]
With the aforementioned fix in the font which should be merged soon, the best way to vertical align the icon with the current font is to is to lower the icon by half of the current font depth (taking y as a reference).

```latex
\newcommand{\simpleIcon}[1]{%
	\raisebox{-0.5\fontchardp\font`y}{%
		\simpleicon{#1}%
	}%
}
```

**Comment by ineshbose** [comment]
Tracking PR: https://github.com/simple-icons/simple-icons-font/pull/171

Thank you a lot for this. I'm waiting for this to merge, and then from this end I'm intending to fix this from the opentype.js font construction way (https://github.com/ineshbose/simple-icons-latex/blob/master/bindings.js#L31), but at the moment I'm not finding the right methods to do it. With that said, I really appreciate your efforts, and if you would consider making a PR (with the JS approach if feasible else redefining the command) so that your contribution is noted.

**Comment by eburghar** [comment]
Hi,

I don't think you need to do anything on your side. It looks ok without the raisebox. I think this should be done on the font itself glyphs by glyphs as some can look misaligned when lied on the descent line and other if lied on the baseline.

If you don't want to wait for the merge, as the font is included in the CTAN package, you can just build the font with the merge applied, copy the otf locally, and `loadSync("SimpleIcons.otf")` in the `binding.js`. That's what I did.

**Comment by ineshbose** [comment]
Thanks for the suggestion! That is definitely one fix along with using the raisebox which one can use temperarily but for the package and developer convenience, it is best that everything is handled by itself without requiring additional configuration or work. I see that the issue has been closed in `simple-icons-font`, and so I am just waiting for the pipeline to also automatically update to that version so that this can be confirmed to be fixed for this package as well and closed off!

**Comment by ineshbose** [comment]
Sorry for taking a while! Package has finally been updated and this is now confirmed to be fix. Thank you very much for your contribution and patience. Closing!

**Comment by ineshbose** [comment]
I want to confirm from users - is this fixed? I noticed that if I compare it to fontawesome5, for example, it's still not in baseline.

![image](https://github.com/ineshbose/simple-icons-latex/assets/56732164/057b74d4-f9c2-4acc-acb1-4c773f025c0b)

MWE:

```tex
\documentclass{article}
\usepackage{simpleicons}
\usepackage{fontawesome5}

\begin{document}

\faBitbucket
\simpleicon{bitbucket}

\end{document}
```
