### ISSUE TITLE
bindings.tex not being updated with releases

### ISSUE THREAD

**Issue by mbertucci47** [ineshbose/simple-icons-latex#24]
While `simpleicons` has had several updates in the meantime, the doc file `bindings.tex` has not been updated in two months. You can see this on the texlive svn: https://tug.org/svn/texlive/trunk/Master/texmf-dist/doc/fonts/simpleicons/
As more evidence, I don't see any mention in the documentation of icons added in the recent releases.

**Comment by ineshbose** [comment]
Hi, this seems to be more related to the registry than the package - you can see releases made here every week and being published to CTAN. https://ctan.org/tex-archive/fonts/simpleicons/doc

Does the registry pull the latest changes?
You can download a release from https://github.com/ineshbose/simple-icons-latex/releases.

**Comment by mbertucci47** [comment]
By "registry" do you mean the texlive svn?

The latest [simpleicons release](https://github.com/simple-icons/simple-icons/releases/tag/9.18.0) mentions three new icons. I do not know what the LaTeX package names these, however if I open the [simpleicons doc](http://mirrors.ctan.org/fonts/simpleicons/doc/simpleicons.pdf) from CTAN and search "activity", "bereal", or "yandex", I find nothing.

**Comment by ineshbose** [comment]
Forgive my ignorance, yes you are right. Let me investigate this and get back to you please.

**Comment by ineshbose** [comment]
I see the issue. The package was being updated, but not the dependency, this was because of a mismatch between the versions caused after https://github.com/ineshbose/simple-icons-latex/commit/37468e12cf467c492fbe418d658c96b18a4f4e3a and according to the script, it's looking for same versions to replace. Committing fix ASAP.

**Comment by ineshbose** [comment]
Thank you for reporting. This should be fixed with v9.19.0 and hopefully will not happen again with the changes in CI.
