### ISSUE TITLE
C# (csharp) Not Displaying Correctly

### ISSUE THREAD

**Issue by avdichiara** [ineshbose/simple-icons-latex#27]
I am trying to use `\simpleicon{csharp}` in Overleaf using pdfLaTeX, and while the icon loads, the shape is wrong. It is displaying as a circle when it should be a hexagon (as shown in the documentation and on simple icons). I have tried switching to XeLaTeX, and the issue persists. Any help is greatly appreciated!

**Comment by ineshbose** [comment]
Hey, thanks for opening an issue.

It seems that the icon was updated https://github.com/simple-icons/simple-icons/pull/9521, and you will see a difference in Overleaf between TeX Live version 2023 and 2024 (as it will use a newer version after v9.15.0).

With that said, newer versions (v13.0.0 onwards) would likely also not give you the C# logo at all (read https://github.com/simple-icons/simple-icons/issues/11236), so my suggestion may be to move-away from using it (or add a custom SVG to your document).
