### ISSUE TITLE
Icon Bug: Single character logos

### ISSUE THREAD

**Issue by ineshbose** [ineshbose/simple-icons-latex#4]
Any icons that do not seem to be rendering as desired can be mentioned here.

**Comment by ineshbose** [comment]
Single character logos (like `e`, `c`, `r`) are not rendering!

**Comment by Rimole** [comment]
\simpleicon{c} with pdfLaTeX: Missing character: There is no [ in font SimpleIcons--simpleiconsTwo! (works with LuaLaTeX and XeLaTeX)

\simpleicon{d} with pdfLaTeX: Missing character: There is no ^^H in font SimpleIcons--simpleiconsThree! (works with LuaLaTeX and XeLaTeX)

\simpleicon{e} with pdfLaTeX: Missing character: There is no p in font SimpleIcons--simpleiconsThree! (works with LuaLaTeX and XeLaTeX)

\simpleicon{less} with pdfLaTeX: icon is not printed, Missing character: There is no � in font SimpleIcons--simpleiconsFive! (works with LuaLaTeX and XeLaTeX)

\simpleicon{v} with pdfLaTeX: icon is not printed, Missing character: There is no � in font SimpleIcons--simpleiconsNine! (works with LuaLaTeX and XeLaTeX)

**Comment by Rimole** [comment]
Fontforge gives the following error messages when opening the SimpleIcons.otf:

```
The glyph withe the name apostrophe is associated with U+EAAA.
  But its name shows that it should be associated with U+02BC.
The glyph withe the name box is associated with U+EB44.
  But its name shows that it should be associated with U+25A1.
The glyph withe the name c is associated with U+EB60.
  But its name shows that it should be associated with U+0063.
The glyph withe the name circle is associated with U+EB91.
  But its name shows that it should be associated with U+25CB.
The glyph withe the name d is associated with U+EC0F.
  But its name shows that it should be associated with U+0064.
The glyph withe the name delta is associated with U+EC37.
  But its name shows that it should be associated with U+03B4.
The glyph withe the name e is associated with U+EC79.
  But its name shows that it should be associated with U+0065.
The glyph withe the name element is associated with U+EC95.
  But its name shows that it should be associated with U+2208.
The glyph withe the name fi is associated with U+ECE4.
  But its name shows that it should be associated with U+FB01.
The glyph withe the name iota is associated with U+EE35.
  But its name shows that it should be associated with U+03B9.
The glyph withe the name less is associated with U+EEC3.
  But its name shows that it should be associated with U+003C.
The glyph withe the name prime is associated with U+F0A7.
  But its name shows that it should be associated with U+2032.
The glyph withe the name r is associated with U+F0F0.
  But its name shows that it should be associated with U+0072.
The glyph withe the name ring is associated with U+F136.
  But its name shows that it should be associated with U+02DA.
The glyph withe the name square is associated with U+F201.
  But its name shows that it should be associated with U+25A1.
The glyph withe the name v is associated with U+F2F9.
  But its name shows that it should be associated with U+0076.
```

**Comment by ineshbose** [comment]
Renaming it makes it show up!

![image](https://github.com/ineshbose/simple-icons-latex/assets/56732164/8aec03b0-bf56-4d71-acc5-c45d04b6b6bf)

I've been under the impression that the single characters are conflicting with literal values of the characters possibly? (I may not be using the right terms)

**Comment by ineshbose** [comment]
Hi, I'm really sorry to get back to you after a while.

I've tried making the change in `simpleicons.sty`, and the glyphs-pdftex.tex files accordingly, but didn't see a fix. This likely needs to be done from the .otf end which I'm working on now.

With that said, apostrophe, box, arc, etc (that are non-single characters) shouldn't have an issue and are appearing on my end - is there an issue you're facing?

**Comment by ineshbose** [comment]
OK so I've fixed a push, but not released yet. I guess I'll keep it open till then.

**Comment by ineshbose** [comment]
Thanks for letting me know about the warnings - that is what I wish to fix next.

Single character logos should now be fixed and released!
